name: Pre-submit check

on:
  push:
    branches: [ "main" ]
  pull_request: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: Install toolchain
        run: |
          make toolchain

      - name: Presubmit check
        run: |
          make presubmit
